### ISSUE TITLE
utilrb does not build on various branches

### ISSUE THREAD

**Issue by psoetens** [orocos-toolchain/utilrb#5]
I'm investigating why utilrb building with 'rake default' fails on my 12.04 system. A git bisect reveals that the commit c38a197 breaks utilrb building, which appeared first on the toolchain-2.6 branch. The bootstrapping was done using :+1: 

> wget http://rock-robotics.org/autoproj_bootstrap
> ruby autoproj_bootstrap git $BUILDCONF_GIT branch=toolchain-2.6

 The error message is:

> running rake default
> INFO: cannot load the Hoe gem, or Hoe fails. Distribution is disabled
> INFO: error message is: ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use 'rdoc/task' (available in RDoc 2.4.2+) instead.
> rake aborted!
> undefined method `<<' for LL():Rake::Scope::EmptyScope
> ./lib/utilrb/doc/rake.rb:45:in`doc'

I've tried the stable branch, master branch, all not working. For stable for example I get:

> $ rake default --trace
> 'utilrb' cannot be build -- loading gem failed: no such file to load -- hoe
> rake aborted!
> Don't know how to build task 'default'
> /home/kaltan/vbox/hudson/jobs/bootstrap-toolchain/workspace/CORBA_IMPL/OMNIORB/TARGET/gnulinux/arch/amd64/branch/toolchain-2.6/compiler/gcc/orocos-toolchain/.gems/gems/rake-10.1.0/lib/rake/task_manager.rb:49:in `[]'
> /home/kaltan/vbox/hudson/jobs/bootstrap-toolchain/workspace/CORBA_IMPL/OMNIORB/TARGET/gnulinux/arch/amd64/branch/toolchain-2.6/compiler/gcc/orocos-toolchain/.gems/gems/rake-10.1.0/lib/rake/application.rb:148:in`invoke_task'
> /home/kaltan/vbox/hudson/jobs/bootstrap-toolchain/workspace/CORBA_IMPL/OMNIORB/TARGET/gnulinux/arch/amd64/branch/toolchain-2.6/compiler/gcc/orocos-toolchain/.gems/gems/rake-10.1.0/lib/rake/application.rb:106:in `top_level'
> /home/kaltan/vbox/hudson/jobs/bootstrap-

etc..

$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

Any clues ?
